server:
  port: 80
spring:
  application:
    name: ShangChouWang-crowd-Zuul
  redis:
    host: 192.168.12.133
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  routes:
    crowd-portal:
      service-id: Zull
      path: /**
  ignored-services: "*"