server:
  port: 2000

spring:
  application:
    name: ShangChouWang-crowd-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/project_crowd?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/


mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml

logging:
  level:
    com.pdsu.wl.crowd.mapper: debug
    com.pdsu.wl.crowd: debug
